version: '3'
volumes:
  postgres_data:
    driver: local
services:
  keycloak-postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: uiouiop
    command: start-dev
    ports:
      - 8080:8080
    depends_on:
      - keycloak-postgres

  opa:
    image: openpolicyagent/opa:0.45.0-rootless
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"

  api:
    build: ./api
    ports:
      - 8081:8081
    depends_on:
      - opa
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      OPA_URL: http://opa:8181

  frontend:
    build: ./taime-spa
    ports:
      - 4200:4200

