on:
  push:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build API
        run: |-
          cd api
          docker build -t "ghcr.io/watcherwhale/taime-api:${{ github.sha }}" .

      - name: Scan API Container
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/watcherwhale/taime-api:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build SPA
        run: |-
          cd taime-spa
          docker build -t "ghcr.io/watcherwhale/taime-spa:${{ github.sha }}" .

      - name: Scan SPA Container
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/watcherwhale/taime-spa:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Scan Postgres Container
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'postgres'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Scan Keycloak Container
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'quay.io/keycloak/keycloak:19.0.3'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Scan OPA Container
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'openpolicyagent/opa:0.45.0-rootless'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
